name: ci

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        kind: ['test']
        go: ['^1.14.2']
        os: [ubuntu-latest, windows-latest, macos-latest]
    name: Go ${{ matrix.go }} ${{ matrix.kind }} in ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Environment
        run: |
          go version
          go env

      - name: Test
        if: matrix.kind == 'test'
        run: go test -v --cover -covermode=count -coverprofile=coverage.out ./...

      - name: Coverage
        if: matrix.kind == 'test' && runner.os == 'macOS' && github.repository == 'axetroy/mocker'
        env:
          COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
        run: |
          GO111MODULE=off go get golang.org/x/tools/cmd/cover
          GO111MODULE=off go get github.com/mattn/goveralls
          $(go env GOPATH)/bin/goveralls -coverprofile=coverage.out -service="GitHub Action" -jobid="${{ github.run_id }}" -jobnumber="${{ github.run_number }}" -reponame="${{ github.repository }}"
